# Generated by Django 5.2.6 on 2025-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('clue', models.TextField()),
                ('image_data', models.BinaryField(blank=True, help_text='Binary image data', null=True)),
                ('goals', models.JSONField(default=list)),
                ('hitareas', models.TextField(blank=True, help_text='Tokenized string of hit areas', null=True)),
                ('before_message_body', models.TextField(blank=True, null=True)),
                ('before_message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('before_message_button', models.CharField(blank=True, max_length=100, null=True)),
                ('before_message_background_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
