# Generated by Django 5.2.6 on 2025-09-13 01:48

import hocus_focus.challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='mode',
            field=models.CharField(blank=True, help_text='Challenge mode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='theme',
            field=models.CharField(blank=True, help_text='Theme identifier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='goals',
            field=models.JSONField(blank=True, default=hocus_focus.challenges.models.default_goals),
        ),
    ]
