# Generated by Django 5.2.6 on 2025-09-10 23:52

import hocus_focus.challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='goals',
            field=models.JSONField(blank=True, default=hocus_focus.challenges.models.default_goals),
        ),
    ]
