# Generated by Django 5.2.6 on 2025-09-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='credit_url',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_test',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_permanent',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_tutorial',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='image_content_type',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='image_size',
        ),
    ]
