# Generated by Django 5.2.6 on 2025-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_mode_challenge_theme_alter_challenge_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='goals',
            field=models.TextField(blank=True, help_text='Comma-separated string of goal times', null=True),
        ),
    ]
